### ISSUE TITLE
Integration into https://github.com/sensity-ai/dot

### ISSUE THREAD

**Issue by giorgiop** [Ailon-Island/Facke#1]
Hi, great work! Looking forward to testing some of these pre-trained models.

Would you be interested to integrate these models into our real-time deepfake project `dot`? https://github.com/sensity-ai/dot
Our faceswap component is already based on SimSwap, so I expect `dot` to be extensible to your models too.

**Comment by Ailon-Island** [comment]
We would appreciate it very much to see our model in `dot`! However, since we are still in a busy summer semester, we may not have much time to collaborate. And to tell the truth, our models did not outperform vanilla SimSwap in our experiments.
