### ISSUE TITLE
The weights on JBox seem to be inaccessible to anyone except university campus

### ISSUE THREAD

**Issue by hcl14** [Ailon-Island/Facke#2]
I tried this downloader but it does not work: https://github.com/hebingchang/pyjbox

**Comment by Ailon-Island** [comment]
Still uploading to release on Baidu Drive… (Our network connection is annoying for Google Drive and OneDrive.)

**Comment by hcl14** [comment]
Ok, thank you very much! Baidu works for me, I can upload to Google or Mega after I have it.

**Comment by Ailon-Island** [comment]
That really helps! So kind of you!

**Comment by Ailon-Island** [comment]
Okay I've uploaded the checkpoints on [Baidu Drive](https://pan.baidu.com/s/17fi7DTDqznTLNultA5AWMQ?pwd=b6az) now! As for the dataset, it is too large to upload. Perhaps you could download from [VGGFace2-HQ](https://github.com/NNNNAI/VGGFace2-HQ) and modify the file structure according to the directory tree we provide.

**Comment by hcl14** [comment]
Thanks! Uploaded to Google:

[https://drive.google.com/drive/folders/19-04v2683KSc14o1ahPh6m4jJJt5X8rt?usp=sharing](https://drive.google.com/drive/folders/19-04v2683KSc14o1ahPh6m4jJJt5X8rt?usp=sharing)

and Mega:

[https://mega.nz/folder/JUpmGYwa#jaHarRjyqKYQXSP8op3zcQ](https://mega.nz/folder/JUpmGYwa#jaHarRjyqKYQXSP8op3zcQ)

**Comment by Ailon-Island** [comment]
A lot of thanks!!!
