### ISSUE TITLE
how to obtain datasets？

### ISSUE THREAD

**Issue by lizian1611** [Ailon-Island/Facke#4]
Hello, I am very interested in your experiment, but the data set cannot be downloaded. Could you please provide the link of Baidu web disk or other ways to obtain it

**Comment by Ailon-Island** [comment]
Hi, thank you for your interest! The modified dataset has been available at Jbox only. Most users had to use their own data process it with our provided code. Sorry for the inconvenience. 
Now, we've uploaded the dataset `.zip` file to Baidu. Please checkout [this link](https://pan.baidu.com/s/17fi7DTDqznTLNultA5AWMQ?pwd=b6az) in `README.md`.
